### ISSUE TITLE
Add back in “Variable fonts in the Google Fonts UI” section when ready

### ISSUE THREAD

**Issue by davelab6** [googlefonts/variable-fonts#119]
There is currently a placeholder for content for the https://googlefonts.github.io/variable-fonts/implementing-variable-fonts/#gf-ui section: 

<img width="723" alt="Screen Shot 2020-02-21 at 11 58 37 AM" src="https://user-images.githubusercontent.com/261579/75059756-98ec8680-54ab-11ea-81f4-6d28b08e7127.png">

This section is also mentioned and linked to at the top of the page:

<img width="619" alt="Screen Shot 2020-02-21 at 12 48 51 PM" src="https://user-images.githubusercontent.com/261579/75059736-912ce200-54ab-11ea-8a8f-c727b644df32.png">

It would be good to remove this placeholder momentarily, so the site doesn't feel like anything is overtly missing, and then add the section back when the content that @jpamental is preparing for it is ready (likely Thursday next week.) 

@kennethormandy please could you comment out those 2 bits for now

**Comment by kennethormandy** [comment]
Done! The first section you mentioned is commented out fully now.

The other one, the line item is hidden:

<img width="755" alt="Screenshot 2020-02-21 11 07 03" src="https://user-images.githubusercontent.com/1581276/75063816-874eb300-549a-11ea-93c0-14c5d9617e64.png">

**Comment by davelab6** [comment]
@kennethormandy thanks for this. Jason sent me the content, so I'm self assigning this for now.

**Comment by jpamental** [comment]
@davelab6 I've got this all queued up and am going to push it live since the new UI is already getting tweeted, etc. Hoping that's OK :)
