### ISSUE TITLE
Update Amstelvar

### ISSUE THREAD

**Issue by davelab6** [googlefonts/variable-fonts#121]
The version of Amstelvar used here is the (now very old) Amstelvar Alpha. Please pick up the latest from https://github.com/TypeNetwork/Amstelvar :) 

<img width="683" alt="Screen Shot 2020-02-21 at 11 53 24 AM" src="https://user-images.githubusercontent.com/261579/75060048-1f08cd00-54ac-11ea-8211-a7ef8f6abece.png">

**Comment by jpamental** [comment]
Grabbing this one since I already had it locally, and am trying out a unicode-range setting in the font-face declarations
