### ISSUE TITLE
Make axis sliders continuous

### ISSUE THREAD

**Issue by davelab6** [googlefonts/variable-fonts#122]
These slides snap from 0 to 1 or -1 to 0 to 1, but should be continuous 

<img width="688" alt="Screen Shot 2020-02-21 at 11 53 10 AM" src="https://user-images.githubusercontent.com/261579/75060097-38aa1480-54ac-11ea-890d-62f11ad430d4.png">
<img width="678" alt="Screen Shot 2020-02-21 at 11 53 01 AM" src="https://user-images.githubusercontent.com/261579/75060098-38aa1480-54ac-11ea-9e39-018e77b73aee.png">

**Comment by jpamental** [comment]
I double-checked and it is passing in a 'data-step' value of 0.01, which should be valid. Not sure why it's not working. I'm pretty sure it worked with the regular MD slider component, and stopped working when we switched to the 'discrete slider' version.

**Comment by jpamental** [comment]
I tested this with the standard MD slider (not the 'discreet' version with the number value popup) and it works with the data-step value as it should, so this may be a bug with the discreet slider component itself. Not really sure what else to try, but we can always drop back to the standard component if we can't get the other one to work.

**Comment by kennethormandy** [comment]
It is a bug, yes: https://github.com/material-components/material-components-web/issues/1426

I have this changed on a branch I’m working on, I would say let’s switch it back to the default rather than discrete? The other option is to treat them all as percentages, but then the value shown is obviously different than what shows up in the code sample.

**Comment by jpamental** [comment]
I'll update the component to let us switch back and forth based on the axis. That should be a decent solution: better for most, but not broken for the rest!

**Comment by jpamental** [comment]
Fixed with #140
